# Mod that makes symbol encounters (visible overworld spawns) pull from the hidden encounter spawn table
[underworld]
active = false

# Mod that makes shiny pokemon visible in the overworld
[overworld_shiny]
active = false

# some sounds:
# "Play_Audience_cheer_riser_rnd"
# "Play_UI_netbattle_rank_up"
# "Play_UI_Lcircuit_Goal"
# "Play_Camp_Cooking_Explosion"
# set to "" for no sound
sound = "Play_Camp_Cooking_Explosion"
# false for regular aura mechanics, true for aura as shiny indicator
repurpose_aura = true
# 0 for regular shiny rate, [1,100] for modified rate
boosted_percentage = 10

# Mod that actively randomizes every new spawn
[randomizer]
active = false

# Mod that lets you tweak the camera speed, pitch range, and field of view
[camera_tweaks]
active = false

# camera speed in degrees per time unit
adjustment_speed = 3.75
# min pitch in degrees
min_pitch = -71.6197244
# max pitch in degrees
max_pitch = 14.3239449
# base camera distance
min_distance = 450.0
# zoomed out camera distance
max_distance = 1000.0